local:
  dialect: mysql
  datasource: admin:admin@1802@tcp(localhost:3306)/auth_service?parseTime=true
  dir: migrations
  table: schema_migrations

dev:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DB}?parseTime=true
  dir: migrations
  table: schema_migrations