version: '3.8'
services:
  mysql:
    container_name: auth_service
    image: bitnami/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin@1802
      - MYSQL_DATABASE=auth_service
      - MYSQL_PASSWORD=admin@1802
      - MYSQL_USER=admin
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin@1802
volumes:
  data:
    driver: local