version: '3.8'
services:
  mysql:
    container_name: auth_service
    image: bitnami/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin@1802
      - MYSQL_DATABASE=auth_service
      - MYSQL_PASSWORD=admin@1802
      - MYSQL_USER=admin
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password

  rabbitmq:
    container_name: auth_service_broker
    image: rabbitmq:3.9.22-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15675:15675"
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"

volumes:
  data:
    driver: local