package errorcode

const (
	ERR_CANNOT_DELETE_ROLE = "ERR_CANNOT_DELETE_ROLE"
	ERR_CANNOT_GET_ROLE    = "ERR_CANNOT_GET_ROLE"
	ERR_ROLE_EXISTING      = "ERR_ROLE_EXISTING"
	ERR_COPY_DATA_FAILED   = "ERR_COPY_DATA_FAILED"

	ERR_PERMISSION_EXISTING = "ERR_PERMISSION_EXISTING"

	ERR_NUM_OF_PERMISSION_ID_NOT_ENOUGH = "ERR_NUM_OF_PERMISSION_ID_NOT_ENOUGH"

	ERR_USER_ROLE_IS_ASSIGNED = "ERR_USER_ROLE_IS_ASSIGNED"

	ERR_USER_EXISTING = "ERR_USER_EXISTING"
)
